dist: trusty

language: node_js
node_js:
  - 10

addons:
  chrome: stable

cache:
  directories:
    - "$HOME/.npm"

install:
  - npm install

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master

script:
  - npm run test-single-run -- --browsers ChromeHeadless
  - (npm start > /dev/null &) && npm run protractor -- --capabilities.chromeOptions.args headless
